image: node:latest

stages:
  - mirror

mirror:
  stage: mirror
  script:
    #github
    - git config --global user.email "runner@$CI_SERVER_HOST"
    - git config --global user.name "runner"
    - git remote remove origin
    - git remote add origin https://firstdorsal:$GITHUB_TOKEN@github.com/$CI_PROJECT_PATH.git
    - curl -u "firstdorsal:$GITHUB_TOKEN" https://api.github.com/user/repos -d "{\"name\":\"$CI_PROJECT_NAME\"}"
    - git push --set-upstream origin HEAD:refs/heads/master -f
    #gitlab
    - git remote remove origin
    - git remote add origin https://firstdorsal:$GITLAB_TOKEN@gitlab.com/$CI_PROJECT_PATH.git
    - curl --request POST "https://gitlab.com/api/v4/projects?visibility=public&private_token=$GITLAB_TOKEN&name=$CI_PROJECT_NAME" ; echo
    - git push --set-upstream origin HEAD:refs/heads/master -f
